apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: PROJECT_ID_TO_REPLACE_readwrite_rolebinding
  namespace: K8S_APP_NAMESPACE_TO_REPLACE
subjects:
- kind: Group
  name: SERVICE_DEVELOPER_ROLE_TO_REPLACE
roleRef:
  kind: Role
  name: PROJECT_ID_TO_REPLACE_readwrite
  apiGroup: rbac.authorization.k8s.io
